# Generated by Django 4.2.30 on 2026-07-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M001State',
            fields=[
                ('state_id', models.IntegerField(db_column='State_ID', primary_key=True, serialize=False)),
                ('state_name', models.CharField(db_column='State_Name', max_length=100)),
                ('state_code', models.CharField(db_column='State_Category', max_length=10)),
            ],
            options={
                'db_table': 'M001_State',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T007Nursery',
            fields=[
                ('nursery_id', models.BigAutoField(db_column='Nursery_ID', primary_key=True, serialize=False)),
                ('nursery_name', models.CharField(db_column='Nursery_Name', max_length=50)),
            ],
            options={
                'db_table': 'T007_Nursery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
