# Generated by Django 4.2.30 on 2026-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMPADFOUser',
            fields=[
                ('userid', models.BigIntegerField(db_column='userid', primary_key=True, serialize=False)),
                ('emailid', models.EmailField(db_column='emailid', max_length=254)),
                ('Fname', models.CharField(db_column='Fname', max_length=100)),
                ('lname', models.CharField(db_column='lname', max_length=100)),
                ('designation', models.CharField(db_column='designation', max_length=255)),
                ('mobilenumber', models.CharField(db_column='mobilenumber', max_length=20)),
                ('forest_division', models.CharField(db_column='forest_division', max_length=255)),
                ('circle', models.CharField(db_column='circle', max_length=255)),
                ('division', models.CharField(db_column='division', max_length=255)),
                ('district', models.CharField(db_column='district', max_length=255)),
                ('state', models.CharField(db_column='state', max_length=255)),
                ('password', models.CharField(db_column='password', max_length=500)),
                ('isverified', models.BooleanField(db_column='isverified')),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'db_table': 'CAMPA_dfo_user',
                'managed': False,
            },
        ),
    ]
