# Generated by Django 4.2.30 on 2026-08-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T030AdvanceBooking',
            fields=[
                ('ab_id', models.BigAutoField(db_column='AB_ID', primary_key=True, serialize=False)),
                ('ab_uniquecode', models.CharField(db_column='AB_UniqueCode', max_length=50)),
                ('ab_district_id', models.BigIntegerField(db_column='AB_District_ID')),
                ('ab_division_id', models.BigIntegerField(db_column='AB_Division_ID')),
                ('ab_soldto', models.CharField(db_column='AB_SoldTo', max_length=2)),
                ('ab_govttype', models.CharField(blank=True, db_column='AB_GovtType', max_length=2, null=True)),
                ('ab_name', models.CharField(db_column='AB_Name', max_length=100)),
                ('ab_staff_name', models.CharField(db_column='AB_Staff_Name', max_length=100)),
                ('ab_staff_contact', models.CharField(db_column='AB_Staff_Contact', max_length=10)),
                ('ab_species_id', models.BigIntegerField(db_column='AB_Species_ID')),
                ('ab_plant_no', models.BigIntegerField(db_column='AB_Plant_No')),
                ('ab_date_avaiable', models.DateField(db_column='AB_Date_Avaiable')),
                ('ab_amount', models.DecimalField(db_column='AB_Amount', decimal_places=2, max_digits=18)),
                ('ab_photo', models.CharField(db_column='AB_PHOTO', max_length=50)),
                ('ab_active', models.CharField(db_column='AB_Active', max_length=1)),
                ('ab_entryby', models.BigIntegerField(db_column='AB_EntryBy')),
                ('ab_entryon', models.DateTimeField(db_column='AB_EntryOn')),
                ('ab_updatedby', models.BigIntegerField(blank=True, db_column='AB_UpdatedBy', null=True)),
                ('ab_updatedon', models.DateTimeField(blank=True, db_column='AB_UpdatedOn', null=True)),
                ('ab_status', models.CharField(blank=True, db_column='AB_Status', max_length=1, null=True)),
                ('ab_approvedby', models.BigIntegerField(blank=True, db_column='AB_ApprovedBy', null=True)),
                ('ab_approvedon', models.DateTimeField(blank=True, db_column='AB_ApprovedOn', null=True)),
            ],
            options={
                'db_table': 'T030_AdvanceBooking',
                'managed': False,
            },
        ),
    ]
