# Generated by Django 4.2.30 on 2026-08-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_t030advancebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='M002District',
            fields=[
                ('district_id', models.AutoField(db_column='District_ID', primary_key=True, serialize=False)),
                ('district_state_id', models.IntegerField(db_column='District_State_ID')),
                ('district_name', models.CharField(db_column='District_Name', max_length=255)),
                ('district_active', models.CharField(blank=True, db_column='District_Active', max_length=1, null=True)),
                ('district_entryby', models.IntegerField(blank=True, db_column='District_Entryby', null=True)),
                ('district_entryon', models.DateTimeField(blank=True, db_column='District_Entryon', null=True)),
            ],
            options={
                'db_table': 'M002_District',
                'managed': False,
            },
        ),
    ]
