# Generated by Django 4.2.30 on 2026-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_m002district'),
    ]

    operations = [
        migrations.CreateModel(
            name='M002Circle',
            fields=[
                ('circle_id', models.AutoField(db_column='Circle_ID', primary_key=True, serialize=False)),
                ('circle_state_id', models.IntegerField(db_column='Circle_State_ID')),
                ('circle_name', models.CharField(db_column='Circle_Name', max_length=255)),
                ('circle_active', models.CharField(blank=True, db_column='Circle_Active', max_length=1, null=True)),
                ('circle_entryby', models.IntegerField(blank=True, db_column='Circle_Entryby', null=True)),
                ('circle_entryon', models.DateTimeField(blank=True, db_column='Circle_Entryon', null=True)),
            ],
            options={
                'db_table': 'M002_Circle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='M003Division',
            fields=[
                ('division_id', models.AutoField(db_column='Division_ID', primary_key=True, serialize=False)),
                ('division_circle_id', models.IntegerField(db_column='Division_Circle_ID')),
                ('division_name', models.CharField(db_column='Division_Name', max_length=255)),
                ('division_active', models.CharField(blank=True, db_column='Division_Active', max_length=1, null=True)),
                ('division_entryby', models.IntegerField(blank=True, db_column='Division_EntryBy', null=True)),
                ('division_entryon', models.DateTimeField(blank=True, db_column='Division_EntryOn', null=True)),
            ],
            options={
                'db_table': 'M003_Division',
                'managed': False,
            },
        ),
    ]
