# Generated by Django 4.2.30 on 2026-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaDfoUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('emailid', models.EmailField(blank=True, max_length=150, null=True)),
                ('fname', models.CharField(blank=True, db_column='Fname', max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('mobilenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('forest_division', models.CharField(blank=True, max_length=100, null=True)),
                ('circle', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('forest_range', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=255)),
                ('isverified', models.IntegerField(default=0)),
                ('tempassword', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_note', models.TextField(blank=True, null=True)),
                ('current_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CAMPA_dfo_user',
                'managed': False,
            },
        ),
    ]
