# Generated by Django 4.2.30 on 2026-08-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaNationalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CAMPA_user',
                'managed': False,
            },
        ),
    ]
