# Generated by Django 4.2.30 on 2026-08-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_auth', '0002_campanationaluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaDfoUser',
        ),
    ]
