# Generated by Django 4.2.30 on 2026-08-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_auth', '0003_delete_campadfouser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campanationaluser',
            table='CAMPA_user_parivesh',
        ),
    ]
