# Generated by Django 4.2.30 on 2026-08-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_auth', '0004_alter_campanationaluser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanationaluser',
            options={},
        ),
    ]
