# Generated by Django 4.2.30 on 2026-08-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_auth', '0005_alter_campanationaluser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanationaluser',
            options={'managed': False},
        ),
    ]
