# Generated by Django 4.2.30 on 2026-08-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_auth', '0006_alter_campanationaluser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campanationaluser',
            table='CAMPA_user',
        ),
    ]
